# Generated by Django 3.1.3 on 2023-05-18 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('userName', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.TextField(max_length=255)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RoomChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=10000)),
                ('userCreate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(max_length=255)),
                ('emailUSer', models.EmailField(max_length=255)),
                ('phoneUser', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTask', models.CharField(max_length=255)),
                ('dataTask', models.TextField(max_length=10000)),
                ('startDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endDate', models.DateTimeField()),
                ('isImportant', models.BooleanField(default=False)),
                ('emailUSer', models.EmailField(blank=True, max_length=255)),
                ('phoneUser', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nameUser', models.CharField(max_length=255)),
                ('date', models.DateTimeField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('timeRest', models.DateTimeField()),
            ],
        ),
    ]
