# Generated by Django 3.1.3 on 2023-05-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
