# Generated by Django 3.1.3 on 2023-05-24 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0002_taskcreation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreation',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 29, 8, 42, 39, 948384)),
        ),
    ]
