# Generated by Django 3.1.3 on 2023-05-26 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0005_auto_20230524_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreation',
            name='finishDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
