# Generated by Django 3.1.3 on 2023-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0007_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagechat',
            old_name='userName',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='taskassignment',
            old_name='nameUser',
            new_name='user_give',
        ),
        migrations.RenameField(
            model_name='taskdone',
            old_name='nameUser',
            new_name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, default='user', max_length=255),
        ),
        migrations.AddField(
            model_name='taskcreation',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
