# Generated by Django 3.1.3 on 2023-06-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0008_auto_20230615_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='passName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='userName',
        ),
    ]
