# Generated by Django 3.1.3 on 2023-06-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0009_auto_20230615_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='passName',
            new_name='pw',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='userName',
            new_name='user',
        ),
    ]
