# Generated by Django 3.1.3 on 2023-06-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0010_auto_20230615_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreation',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
