# Generated by Django 3.1.3 on 2023-06-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0011_taskcreation_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='taskcreation',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
