# Generated by Django 3.1.3 on 2023-06-23 03:41

import TaskManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0011_taskcreation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/<django.db.models.fields.CharField>', validators=[TaskManagement.models.validate_file_extension]),
        ),
    ]
