# Generated by Django 3.1.3 on 2023-07-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0012_auto_20230629_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCreationAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTask', models.CharField(max_length=255)),
                ('dataTask', models.TextField(max_length=10000)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('endDate', models.IntegerField()),
                ('isImportant', models.BooleanField(default=False)),
                ('emailUSer', models.EmailField(blank=True, max_length=255)),
                ('phoneUser', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='api_token',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
