# Generated by Django 3.1.3 on 2023-07-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0013_auto_20230701_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcreation',
            name='username',
        ),
    ]
