# Generated by Django 3.1.3 on 2023-07-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0014_remove_taskcreation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcreation',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
