# Generated by Django 3.1.3 on 2023-06-23 12:47

import TaskManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0014_auto_20230623_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcreation',
            name='file',
            field=models.FileField(upload_to='upload_files', validators=[TaskManagement.models.validate_file_extension]),
        ),
    ]
