# Generated by Django 3.1.3 on 2023-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0021_auto_20230624_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='taskcreation',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
